### ISSUE TITLE
[Suggestion] embed now playing and queue with buttons

### ISSUE THREAD

**Issue by rafalohaki** [febkosq8/Jappan#1]
Would be great to have some buttons for player

For example like this:
![image](https://user-images.githubusercontent.com/20607107/222933451-8cdc0805-98b9-41fb-8432-c5ca92ebcf60.png)

bot playing music without problems btw

**Comment by febkosq8** [comment]
Try the following:

Deleting node_modules and package-lock files.
Then run npm i
and try again

**Comment by febkosq8** [comment]
Try the following:

Delete node_modules and package-lock file.
Then run npm i
and try again

**Comment by febkosq8** [comment]
Will keep in mind, during next feature run.

**Comment by febkosq8** [comment]
Question : Should I keep the emoji in button or remove it ?
![image](https://user-images.githubusercontent.com/33223665/223105022-ba209eba-f208-4d94-8a07-0ef17767cb5f.png)

**Comment by rafalohaki** [comment]
its looking good with buttons

**Comment by febkosq8** [comment]
Implemented in  34c37413237fc748a60ad98c749732c08580b86c.
The prod bot has this feature live.

**Comment by rafalohaki** [comment]
btw i tried to use bot and it needs config.js 
tried like this
```module.exports = {
  token: 'tokenexample',
};```

but its not working
